[project]
name = "crop-doctor"
version = "0.1.0"
dependencies = [
    "torch==2.2.2",
    "torchvision==0.17.2",
    "Flask==3.0.0",
    "Pillow==10.2.0"
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cpu" }
torchvision = { index = "pytorch-cpu" }